# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ESCAPE_PYRAMID.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStackedWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 431)
        MainWindow.setMinimumSize(QSize(800, 431))
        MainWindow.setMaximumSize(QSize(800, 431))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.paginas = QStackedWidget(self.centralwidget)
        self.paginas.setObjectName(u"paginas")
        self.paginas.setGeometry(QRect(0, 0, 801, 441))
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.img_1 = QLabel(self.page_1)
        self.img_1.setObjectName(u"img_1")
        self.img_1.setGeometry(QRect(-10, 0, 811, 431))
        self.img_1.setPixmap(QPixmap(u"Imagens/ESCAPE PYRAMID.gif"))
        self.img_1.setScaledContents(True)
        self.btn_jogar = QPushButton(self.page_1)
        self.btn_jogar.setObjectName(u"btn_jogar")
        self.btn_jogar.setGeometry(QRect(360, 270, 91, 23))
        self.btn_jogar.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.btn_jogar_2 = QPushButton(self.page_2)
        self.btn_jogar_2.setObjectName(u"btn_jogar_2")
        self.btn_jogar_2.setGeometry(QRect(380, 190, 20, 16))
        self.btn_jogar_2.setStyleSheet(u"background-color: transparent")
        self.img_2 = QLabel(self.page_2)
        self.img_2.setObjectName(u"img_2")
        self.img_2.setGeometry(QRect(0, 0, 811, 431))
        self.img_2.setPixmap(QPixmap(u"Imagens/2.png"))
        self.img_2.setScaledContents(True)
        self.btn_porta = QPushButton(self.page_2)
        self.btn_porta.setObjectName(u"btn_porta")
        self.btn_porta.setGeometry(QRect(150, 110, 61, 91))
        self.btn_porta.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_2)
        self.img_2.raise_()
        self.btn_jogar_2.raise_()
        self.btn_porta.raise_()
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.img_dica_1 = QLabel(self.page_3)
        self.img_dica_1.setObjectName(u"img_dica_1")
        self.img_dica_1.setGeometry(QRect(0, 0, 811, 431))
        self.img_dica_1.setPixmap(QPixmap(u"Imagens/3.png"))
        self.img_dica_1.setScaledContents(True)
        self.btn_gigante_1 = QPushButton(self.page_3)
        self.btn_gigante_1.setObjectName(u"btn_gigante_1")
        self.btn_gigante_1.setGeometry(QRect(0, 0, 801, 421))
        self.btn_gigante_1.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.img_porta = QLabel(self.page_4)
        self.img_porta.setObjectName(u"img_porta")
        self.img_porta.setGeometry(QRect(0, 0, 811, 431))
        self.img_porta.setPixmap(QPixmap(u"Imagens/4.png"))
        self.img_porta.setScaledContents(True)
        self.btn_portaLua = QPushButton(self.page_4)
        self.btn_portaLua.setObjectName(u"btn_portaLua")
        self.btn_portaLua.setGeometry(QRect(390, 80, 41, 41))
        self.btn_portaLua.setStyleSheet(u"background-color: transparent")
        self.btn_portaLua_errado = QPushButton(self.page_4)
        self.btn_portaLua_errado.setObjectName(u"btn_portaLua_errado")
        self.btn_portaLua_errado.setGeometry(QRect(370, 140, 81, 101))
        self.btn_portaLua_errado.setStyleSheet(u"background-color: transparent")
        self.img_voltar = QLabel(self.page_4)
        self.img_voltar.setObjectName(u"img_voltar")
        self.img_voltar.setGeometry(QRect(20, 360, 81, 51))
        self.img_voltar.setPixmap(QPixmap(u"Imagens/voltar_claro.png"))
        self.img_voltar.setScaledContents(True)
        self.btn_voltar_p2 = QPushButton(self.page_4)
        self.btn_voltar_p2.setObjectName(u"btn_voltar_p2")
        self.btn_voltar_p2.setGeometry(QRect(20, 350, 81, 71))
        self.btn_voltar_p2.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.btn_gigante_2 = QPushButton(self.page_5)
        self.btn_gigante_2.setObjectName(u"btn_gigante_2")
        self.btn_gigante_2.setGeometry(QRect(0, 0, 801, 421))
        self.btn_gigante_2.setStyleSheet(u"background-color: transparent")
        self.img_porta_2 = QLabel(self.page_5)
        self.img_porta_2.setObjectName(u"img_porta_2")
        self.img_porta_2.setGeometry(QRect(0, 0, 811, 431))
        self.img_porta_2.setPixmap(QPixmap(u"Imagens/5.png"))
        self.img_porta_2.setScaledContents(True)
        self.inputUsuario = QLineEdit(self.page_5)
        self.inputUsuario.setObjectName(u"inputUsuario")
        self.inputUsuario.setGeometry(QRect(260, 200, 241, 31))
        self.btn_enviar = QPushButton(self.page_5)
        self.btn_enviar.setObjectName(u"btn_enviar")
        self.btn_enviar.setGeometry(QRect(510, 200, 41, 31))
        self.btn_enviar.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_5)
        self.img_porta_2.raise_()
        self.btn_gigante_2.raise_()
        self.inputUsuario.raise_()
        self.btn_enviar.raise_()
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.img_apos_porta = QLabel(self.page_6)
        self.img_apos_porta.setObjectName(u"img_apos_porta")
        self.img_apos_porta.setGeometry(QRect(-10, 0, 811, 431))
        self.img_apos_porta.setPixmap(QPixmap(u"Imagens/6.png"))
        self.img_apos_porta.setScaledContents(True)
        self.btn_macaquinho = QPushButton(self.page_6)
        self.btn_macaquinho.setObjectName(u"btn_macaquinho")
        self.btn_macaquinho.setGeometry(QRect(250, 230, 51, 51))
        self.btn_macaquinho.setStyleSheet(u"background-color: transparent")
        self.btn_macaquinho_errado1 = QPushButton(self.page_6)
        self.btn_macaquinho_errado1.setObjectName(u"btn_macaquinho_errado1")
        self.btn_macaquinho_errado1.setGeometry(QRect(20, 60, 141, 241))
        self.btn_macaquinho_errado1.setStyleSheet(u"background-color: transparent")
        self.btn_macaquinho_errado2 = QPushButton(self.page_6)
        self.btn_macaquinho_errado2.setObjectName(u"btn_macaquinho_errado2")
        self.btn_macaquinho_errado2.setGeometry(QRect(410, 120, 51, 111))
        self.btn_macaquinho_errado2.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_6)
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.btn_macaquinho_3 = QPushButton(self.page_7)
        self.btn_macaquinho_3.setObjectName(u"btn_macaquinho_3")
        self.btn_macaquinho_3.setGeometry(QRect(390, 110, 16, 16))
        self.btn_macaquinho_3.setStyleSheet(u"background-color: transparent")
        self.img_apos_porta_3 = QLabel(self.page_7)
        self.img_apos_porta_3.setObjectName(u"img_apos_porta_3")
        self.img_apos_porta_3.setGeometry(QRect(0, 0, 811, 431))
        self.img_apos_porta_3.setPixmap(QPixmap(u"Imagens/7.png"))
        self.img_apos_porta_3.setScaledContents(True)
        self.img_voltar_2 = QLabel(self.page_7)
        self.img_voltar_2.setObjectName(u"img_voltar_2")
        self.img_voltar_2.setGeometry(QRect(20, 350, 81, 51))
        self.img_voltar_2.setPixmap(QPixmap(u"Imagens/voltar_claro.png"))
        self.img_voltar_2.setScaledContents(True)
        self.btn_voltar_p6 = QPushButton(self.page_7)
        self.btn_voltar_p6.setObjectName(u"btn_voltar_p6")
        self.btn_voltar_p6.setGeometry(QRect(20, 340, 81, 71))
        self.btn_voltar_p6.setStyleSheet(u"background-color: transparent")
        self.btn_macaquinho_resposta = QPushButton(self.page_7)
        self.btn_macaquinho_resposta.setObjectName(u"btn_macaquinho_resposta")
        self.btn_macaquinho_resposta.setGeometry(QRect(350, 170, 101, 141))
        self.btn_macaquinho_resposta.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_7)
        self.img_apos_porta_3.raise_()
        self.btn_macaquinho_3.raise_()
        self.img_voltar_2.raise_()
        self.btn_voltar_p6.raise_()
        self.btn_macaquinho_resposta.raise_()
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.btn_gigante_3 = QPushButton(self.page_8)
        self.btn_gigante_3.setObjectName(u"btn_gigante_3")
        self.btn_gigante_3.setGeometry(QRect(0, 0, 801, 421))
        self.btn_gigante_3.setStyleSheet(u"background-color: transparent")
        self.img_dica_2 = QLabel(self.page_8)
        self.img_dica_2.setObjectName(u"img_dica_2")
        self.img_dica_2.setGeometry(QRect(0, 0, 811, 431))
        self.img_dica_2.setPixmap(QPixmap(u"Imagens/8.png"))
        self.img_dica_2.setScaledContents(True)
        self.paginas.addWidget(self.page_8)
        self.img_dica_2.raise_()
        self.btn_gigante_3.raise_()
        self.page_9 = QWidget()
        self.page_9.setObjectName(u"page_9")
        self.btn_enviar_2 = QPushButton(self.page_9)
        self.btn_enviar_2.setObjectName(u"btn_enviar_2")
        self.btn_enviar_2.setGeometry(QRect(510, 200, 41, 31))
        self.btn_enviar_2.setStyleSheet(u"background-color: transparent")
        self.img_macaquinho = QLabel(self.page_9)
        self.img_macaquinho.setObjectName(u"img_macaquinho")
        self.img_macaquinho.setGeometry(QRect(0, 0, 811, 431))
        self.img_macaquinho.setPixmap(QPixmap(u"Imagens/9.png"))
        self.img_macaquinho.setScaledContents(True)
        self.inputUsuario_2 = QLineEdit(self.page_9)
        self.inputUsuario_2.setObjectName(u"inputUsuario_2")
        self.inputUsuario_2.setGeometry(QRect(260, 200, 241, 31))
        self.btn_gigante_4 = QPushButton(self.page_9)
        self.btn_gigante_4.setObjectName(u"btn_gigante_4")
        self.btn_gigante_4.setGeometry(QRect(0, 0, 801, 421))
        self.btn_gigante_4.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_9)
        self.img_macaquinho.raise_()
        self.btn_gigante_4.raise_()
        self.btn_enviar_2.raise_()
        self.inputUsuario_2.raise_()
        self.page_10 = QWidget()
        self.page_10.setObjectName(u"page_10")
        self.img_caminhos = QLabel(self.page_10)
        self.img_caminhos.setObjectName(u"img_caminhos")
        self.img_caminhos.setGeometry(QRect(-10, 0, 811, 431))
        self.img_caminhos.setPixmap(QPixmap(u"Imagens/10.png"))
        self.img_caminhos.setScaledContents(True)
        self.btn_caminho2 = QPushButton(self.page_10)
        self.btn_caminho2.setObjectName(u"btn_caminho2")
        self.btn_caminho2.setGeometry(QRect(560, 240, 131, 131))
        self.btn_caminho2.setStyleSheet(u"background-color: transparent")
        self.btn_caminho1_errado = QPushButton(self.page_10)
        self.btn_caminho1_errado.setObjectName(u"btn_caminho1_errado")
        self.btn_caminho1_errado.setGeometry(QRect(240, 240, 91, 121))
        self.btn_caminho1_errado.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_10)
        self.page_11 = QWidget()
        self.page_11.setObjectName(u"page_11")
        self.img_altar = QLabel(self.page_11)
        self.img_altar.setObjectName(u"img_altar")
        self.img_altar.setGeometry(QRect(0, 0, 811, 431))
        self.img_altar.setPixmap(QPixmap(u"Imagens/11.png"))
        self.img_altar.setScaledContents(True)
        self.btn_dica_3 = QPushButton(self.page_11)
        self.btn_dica_3.setObjectName(u"btn_dica_3")
        self.btn_dica_3.setGeometry(QRect(390, 230, 21, 16))
        self.btn_dica_3.setStyleSheet(u"background-color: transparent")
        self.btn_altar = QPushButton(self.page_11)
        self.btn_altar.setObjectName(u"btn_altar")
        self.btn_altar.setGeometry(QRect(380, 90, 61, 61))
        self.btn_altar.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_11)
        self.page_12 = QWidget()
        self.page_12.setObjectName(u"page_12")
        self.btn_gigante_5 = QPushButton(self.page_12)
        self.btn_gigante_5.setObjectName(u"btn_gigante_5")
        self.btn_gigante_5.setGeometry(QRect(0, 10, 801, 421))
        self.btn_gigante_5.setStyleSheet(u"background-color: transparent")
        self.img_altar_2 = QLabel(self.page_12)
        self.img_altar_2.setObjectName(u"img_altar_2")
        self.img_altar_2.setGeometry(QRect(0, 0, 811, 431))
        self.img_altar_2.setPixmap(QPixmap(u"Imagens/12.png"))
        self.img_altar_2.setScaledContents(True)
        self.paginas.addWidget(self.page_12)
        self.img_altar_2.raise_()
        self.btn_gigante_5.raise_()
        self.page_13 = QWidget()
        self.page_13.setObjectName(u"page_13")
        self.btn_gigante_6 = QPushButton(self.page_13)
        self.btn_gigante_6.setObjectName(u"btn_gigante_6")
        self.btn_gigante_6.setGeometry(QRect(0, 0, 801, 421))
        self.btn_gigante_6.setStyleSheet(u"background-color: transparent")
        self.img_macaquinho_2 = QLabel(self.page_13)
        self.img_macaquinho_2.setObjectName(u"img_macaquinho_2")
        self.img_macaquinho_2.setGeometry(QRect(0, 0, 811, 431))
        self.img_macaquinho_2.setPixmap(QPixmap(u"Imagens/13.png"))
        self.img_macaquinho_2.setScaledContents(True)
        self.inputUsuario_3 = QLineEdit(self.page_13)
        self.inputUsuario_3.setObjectName(u"inputUsuario_3")
        self.inputUsuario_3.setGeometry(QRect(250, 200, 241, 31))
        self.btn_enviar_3 = QPushButton(self.page_13)
        self.btn_enviar_3.setObjectName(u"btn_enviar_3")
        self.btn_enviar_3.setGeometry(QRect(500, 200, 41, 31))
        self.btn_enviar_3.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_13)
        self.img_macaquinho_2.raise_()
        self.btn_gigante_6.raise_()
        self.inputUsuario_3.raise_()
        self.btn_enviar_3.raise_()
        self.page_14 = QWidget()
        self.page_14.setObjectName(u"page_14")
        self.img_lobos = QLabel(self.page_14)
        self.img_lobos.setObjectName(u"img_lobos")
        self.img_lobos.setGeometry(QRect(0, 0, 811, 431))
        self.img_lobos.setPixmap(QPixmap(u"Imagens/14.png"))
        self.img_lobos.setScaledContents(True)
        self.btn_lobo_certo = QPushButton(self.page_14)
        self.btn_lobo_certo.setObjectName(u"btn_lobo_certo")
        self.btn_lobo_certo.setGeometry(QRect(570, 120, 21, 71))
        self.btn_lobo_certo.setStyleSheet(u"background-color: transparent")
        self.btn_portaSaida = QPushButton(self.page_14)
        self.btn_portaSaida.setObjectName(u"btn_portaSaida")
        self.btn_portaSaida.setGeometry(QRect(370, 50, 81, 181))
        self.btn_portaSaida.setStyleSheet(u"background-color: transparent")
        self.btn_lobo_errado1 = QPushButton(self.page_14)
        self.btn_lobo_errado1.setObjectName(u"btn_lobo_errado1")
        self.btn_lobo_errado1.setGeometry(QRect(140, 190, 41, 61))
        self.btn_lobo_errado1.setStyleSheet(u"background-color: transparent")
        self.btn_lobo_errado2 = QPushButton(self.page_14)
        self.btn_lobo_errado2.setObjectName(u"btn_lobo_errado2")
        self.btn_lobo_errado2.setGeometry(QRect(220, 220, 41, 61))
        self.btn_lobo_errado2.setStyleSheet(u"background-color: transparent")
        self.btn_lobo_errado3 = QPushButton(self.page_14)
        self.btn_lobo_errado3.setObjectName(u"btn_lobo_errado3")
        self.btn_lobo_errado3.setGeometry(QRect(380, 250, 41, 61))
        self.btn_lobo_errado3.setStyleSheet(u"background-color: transparent")
        self.btn_lobo_errado4 = QPushButton(self.page_14)
        self.btn_lobo_errado4.setObjectName(u"btn_lobo_errado4")
        self.btn_lobo_errado4.setGeometry(QRect(610, 220, 41, 61))
        self.btn_lobo_errado4.setStyleSheet(u"background-color: transparent")
        self.btn_lobo_errado5 = QPushButton(self.page_14)
        self.btn_lobo_errado5.setObjectName(u"btn_lobo_errado5")
        self.btn_lobo_errado5.setGeometry(QRect(680, 360, 41, 61))
        self.btn_lobo_errado5.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_14)
        self.page_15 = QWidget()
        self.page_15.setObjectName(u"page_15")
        self.img_lobos_2 = QLabel(self.page_15)
        self.img_lobos_2.setObjectName(u"img_lobos_2")
        self.img_lobos_2.setGeometry(QRect(0, 0, 811, 431))
        self.img_lobos_2.setPixmap(QPixmap(u"Imagens/15.png"))
        self.img_lobos_2.setScaledContents(True)
        self.btn_gigante_7 = QPushButton(self.page_15)
        self.btn_gigante_7.setObjectName(u"btn_gigante_7")
        self.btn_gigante_7.setGeometry(QRect(0, 0, 801, 421))
        self.btn_gigante_7.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_15)
        self.page_16 = QWidget()
        self.page_16.setObjectName(u"page_16")
        self.img_saida = QLabel(self.page_16)
        self.img_saida.setObjectName(u"img_saida")
        self.img_saida.setGeometry(QRect(-5, 0, 811, 431))
        self.img_saida.setPixmap(QPixmap(u"Imagens/16.png"))
        self.img_saida.setScaledContents(True)
        self.btn_saida = QPushButton(self.page_16)
        self.btn_saida.setObjectName(u"btn_saida")
        self.btn_saida.setGeometry(QRect(390, 120, 291, 221))
        self.btn_saida.setStyleSheet(u"background-color: transparent")
        self.paginas.addWidget(self.page_16)
        self.page_17 = QWidget()
        self.page_17.setObjectName(u"page_17")
        self.img_saida_2 = QLabel(self.page_17)
        self.img_saida_2.setObjectName(u"img_saida_2")
        self.img_saida_2.setGeometry(QRect(-5, 0, 811, 431))
        self.img_saida_2.setPixmap(QPixmap(u"Imagens/17.png"))
        self.img_saida_2.setScaledContents(True)
        self.paginas.addWidget(self.page_17)
        self.chance5 = QWidget()
        self.chance5.setObjectName(u"chance5")
        self.img_chance5 = QLabel(self.chance5)
        self.img_chance5.setObjectName(u"img_chance5")
        self.img_chance5.setGeometry(QRect(0, 0, 801, 431))
        self.img_chance5.setPixmap(QPixmap(u"Imagens/18.png"))
        self.img_chance5.setScaledContents(True)
        self.paginas.addWidget(self.chance5)
        self.chance4 = QWidget()
        self.chance4.setObjectName(u"chance4")
        self.img_chance4 = QLabel(self.chance4)
        self.img_chance4.setObjectName(u"img_chance4")
        self.img_chance4.setGeometry(QRect(0, 0, 801, 431))
        self.img_chance4.setPixmap(QPixmap(u"Imagens/19.png"))
        self.img_chance4.setScaledContents(True)
        self.paginas.addWidget(self.chance4)
        self.chance3 = QWidget()
        self.chance3.setObjectName(u"chance3")
        self.img_chance3 = QLabel(self.chance3)
        self.img_chance3.setObjectName(u"img_chance3")
        self.img_chance3.setGeometry(QRect(0, 0, 801, 431))
        self.img_chance3.setPixmap(QPixmap(u"Imagens/20.png"))
        self.img_chance3.setScaledContents(True)
        self.paginas.addWidget(self.chance3)
        self.chance2 = QWidget()
        self.chance2.setObjectName(u"chance2")
        self.img_chance2 = QLabel(self.chance2)
        self.img_chance2.setObjectName(u"img_chance2")
        self.img_chance2.setGeometry(QRect(0, 0, 801, 431))
        self.img_chance2.setPixmap(QPixmap(u"Imagens/21.png"))
        self.img_chance2.setScaledContents(True)
        self.paginas.addWidget(self.chance2)
        self.chance1 = QWidget()
        self.chance1.setObjectName(u"chance1")
        self.img_chance1 = QLabel(self.chance1)
        self.img_chance1.setObjectName(u"img_chance1")
        self.img_chance1.setGeometry(QRect(0, 0, 801, 431))
        self.img_chance1.setPixmap(QPixmap(u"Imagens/22.png"))
        self.img_chance1.setScaledContents(True)
        self.paginas.addWidget(self.chance1)
        self.gameover = QWidget()
        self.gameover.setObjectName(u"gameover")
        self.gameover_2 = QLabel(self.gameover)
        self.gameover_2.setObjectName(u"gameover_2")
        self.gameover_2.setGeometry(QRect(0, 0, 801, 431))
        self.gameover_2.setPixmap(QPixmap(u"Imagens/23.png"))
        self.gameover_2.setScaledContents(True)
        self.btn_recomecar = QPushButton(self.gameover)
        self.btn_recomecar.setObjectName(u"btn_recomecar")
        self.btn_recomecar.setGeometry(QRect(350, 330, 101, 41))
        self.paginas.addWidget(self.gameover)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.img_1.setText("")
        self.btn_jogar.setText("")
        self.btn_jogar_2.setText("")
        self.img_2.setText("")
        self.btn_porta.setText("")
        self.img_dica_1.setText("")
        self.btn_gigante_1.setText("")
        self.img_porta.setText("")
        self.btn_portaLua.setText("")
        self.btn_portaLua_errado.setText("")
        self.img_voltar.setText("")
        self.btn_voltar_p2.setText("")
        self.btn_gigante_2.setText("")
        self.img_porta_2.setText("")
        self.btn_enviar.setText(QCoreApplication.translate("MainWindow", u"ENVIAR", None))
        self.img_apos_porta.setText("")
        self.btn_macaquinho.setText("")
        self.btn_macaquinho_errado1.setText("")
        self.btn_macaquinho_errado2.setText("")
        self.btn_macaquinho_3.setText("")
        self.img_apos_porta_3.setText("")
        self.img_voltar_2.setText("")
        self.btn_voltar_p6.setText("")
        self.btn_macaquinho_resposta.setText("")
        self.btn_gigante_3.setText("")
        self.img_dica_2.setText("")
        self.btn_enviar_2.setText(QCoreApplication.translate("MainWindow", u"ENVIAR", None))
        self.img_macaquinho.setText("")
        self.btn_gigante_4.setText("")
        self.img_caminhos.setText("")
        self.btn_caminho2.setText("")
        self.btn_caminho1_errado.setText("")
        self.img_altar.setText("")
        self.btn_dica_3.setText("")
        self.btn_altar.setText("")
        self.btn_gigante_5.setText("")
        self.img_altar_2.setText("")
        self.btn_gigante_6.setText("")
        self.img_macaquinho_2.setText("")
        self.btn_enviar_3.setText(QCoreApplication.translate("MainWindow", u"ENVIAR", None))
        self.img_lobos.setText("")
        self.btn_lobo_certo.setText("")
        self.btn_portaSaida.setText("")
        self.btn_lobo_errado1.setText("")
        self.btn_lobo_errado2.setText("")
        self.btn_lobo_errado3.setText("")
        self.btn_lobo_errado4.setText("")
        self.btn_lobo_errado5.setText("")
        self.img_lobos_2.setText("")
        self.btn_gigante_7.setText("")
        self.img_saida.setText("")
        self.btn_saida.setText("")
        self.img_saida_2.setText("")
        self.img_chance5.setText("")
        self.img_chance4.setText("")
        self.img_chance3.setText("")
        self.img_chance2.setText("")
        self.img_chance1.setText("")
        self.gameover_2.setText("")
        self.btn_recomecar.setText("")
    # retranslateUi

